# ~/.config/starship.toml
# Starship prompt config tokyo night config.
# Docs: https://starship.rs/config/

# Use the Catppuccin Mocha palette defined at the bottom.
palette = "tokyonight"

format = """
$os\
$directory\
$git_branch\
$git_status\
$c$python$rust$java$nodejs\
$cmd_duration\
$line_break\
$character"""

add_newline = true

[os]
disabled = false
format = "[$symbol]($style)"
style = "fg:blue"
[os.symbols]
Arch = "󰣇 "
Ubuntu = "󰕈 "
Debian = "󰣚 "
Fedora = "󰣛 "
Linux = " "

[directory]
style = "fg:peach bold"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = ""
"Music" = "󰝚 "
"Pictures" = ""
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:green"
format = "[$symbol $branch ]($style)"

[git_status]
style = "fg:yellow"
format = "[$all_status$ahead_behind ]($style)"

[c]
symbol = " "
style = "fg:teal"
format = "[$symbol($version) ]($style)"
[python]
symbol = " "
style = "fg:teal"
format = "[$symbol($version) ]($style)"
[rust]
symbol = " "
style = "fg:teal"
format = "[$symbol($version) ]($style)"
[java]
symbol = " "
style = "fg:teal"
format = "[$symbol($version) ]($style)"
[nodejs]
symbol = ""
style = "fg:blue"
format = "[$symbol($version) ]($style)"

[cmd_duration]
min_time = 2000
style = "fg:subtext0"
format = "[ 󱎫 $duration ]($style)"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

# ─────────────────────────────────────────────
# Tokyo Night palette
# ─────────────────────────────────────────────
[palettes.tokyonight]
rosewater = "#f7768e"
flamingo  = "#f7768e"
pink      = "#bb9af7"
mauve     = "#bb9af7"
red       = "#f7768e"
maroon    = "#f7768e"
peach     = "#e0af68"
yellow    = "#e0af68"
green     = "#9ece6a"
teal      = "#7dcfff"
sky       = "#7dcfff"
sapphire  = "#7aa2f7"
blue      = "#7aa2f7"
lavender  = "#bb9af7"
text      = "#c0caf5"
subtext1  = "#a9b1d6"
subtext0  = "#565f89"
overlay2  = "#565f89"
overlay1  = "#565f89"
overlay0  = "#414868"
surface2  = "#414868"
surface1  = "#292e42"
surface0  = "#1f2335"
base      = "#1a1b26"
mantle    = "#16161e"
crust     = "#13141c"
